name: ww_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  get_it: ^7.7.0
  intl:
  cached_network_image: ^3.3.1
  in_app_review: ^2.0.9
  flutter_gen: ^5.8.0
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  oktoast: ^3.4.0
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.9.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  talker_dio_logger: ^4.4.1
  talker: ^4.4.1
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0
  path_provider: ^2.1.3
  flutter_libphonenumber: ^2.2.3
  share_plus: ^10.0.2
  drift: ^2.2.0
  image_picker: ^1.1.2
  email_validator: ^3.0.0
  url_launcher:
  json_serializable: ^6.8.0
  sqlite3_flutter_libs: ^0.5.10
  barcode_widget: ^2.0.4
  flutter_native_splash: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  drift_dev: ^2.2.0+1
  flutter_gen_runner:

flutter_icons:
  image_path: "assets/logo/icons2.png"
  android: true
  remove_alpha_ios: true
  ios: true

flutter_native_splash:
  image: "assets/logo/icon_rounded.png"
  color: '#0F0F10'

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/logo/
    - assets/images/
    - assets/customize/
    - assets/customize/pattern/
    - assets/social-media/